### ISSUE TITLE
Switch lisence

### ISSUE THREAD

**Issue by Mojken** [kkrypt0nn/Python-Discord-Bot-Template#19]
The Apache License gives you copyright ownership of the template, which means that bots made using this template are (partially) owned by you. This severely limits how we can use the template. I suggest using a copyleft license such as GPL.

**Comment by Nyvil** [comment]
Yes, that is wanted and expected. 
While apache gives us partly the ownership of any bot that uses our template, GPL requires you to disclose the source and use the same license.
Therefore we'll stick with Apache 2.0 :)

**Comment by kkrypt0nn** [comment]
I won't switch license, as stated in the [README.md](https://github.com/kkrypt0nn/Python-Discord-Bot-Template/blob/master/README.md) file you should still give credits to me, who did this template and worked a lot on it:

> If you play to use this template to make your own template or bot, please give me credits, it would be greatly appreciated.

I might rephrase it since it might not be understandable.

We don't fully own the bot that uses this template but only partly. This is, hopefully, understandable since many people will keep everything I made and add a few commands.
In addition, GPL would make you disclose the source code of your own bots, which not everyone wants.
