### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Jay-Hyun** [kkrypt0nn/Python-Discord-Bot-Template#4]
[message.txt](https://github.com/kkrypt0nn/Python-Discord-Bot-Template/files/5179549/message.txt)

Tell me how to fix it :(

**Comment by kkrypt0nn** [comment]
If you're getting the `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)` error on a Windows host do the following:

Download and __**install**__ this certificate here: <https://crt.sh/?id=2835394%3E>
--> It can be installed by double clicking the file and installing it to Local Computer, download link location: <https://beans-took-my-kids.reeee.ee/38qB2n.png%3E>

For those curious, it was caused by this:
<https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117LT%3E>
