### ISSUE TITLE
Add Intents and remove a few uneeded things that where done wrong

### ISSUE THREAD

**Issue by Lost1419** [kkrypt0nn/Python-Discord-Bot-Template#8]

**Comment by kkrypt0nn** [comment]
I will add intents right now.

More information about the things that were done 'wrong'?

**Comment by Lost1419** [comment]
Sure, one you could subclass help instead of hard coding it in. There is a `commands.has_permission` for permission checks and `commands.is_owner` to check if there owner. For removing help it is recommended to do `help_command=None` in the bot constructor (`commands.Bot`).  You can also use `owner_ids` in there too to add multiple owners of the bot

**Comment by kkrypt0nn** [comment]
Interesting, never heard of some stuff, thanks.
For the help command I'm good with hard coding it since it's easier for newcomers to understand, same to remove the help command. It's a personal choice.
For the `has_permission` I know it's existing, just never used it since people might want to have commands to be executed by the bot owners and the server admins and I prefer to use an `if` check.
I however never heard of `owner_ids` will take a look, but this is not interesting for me since people might want to add other people as owner of the bot **only** in the code itself.

Will take a further look to see what I could change in the future.

**Comment by Lost1419** [comment]
You can do both `has_permission` and `is_owner` with `check`. That may not be right so let me double check for you

**Comment by Lost1419** [comment]
Whoops it's `check_any`

**Comment by kkrypt0nn** [comment]
Well thanks, will take a look to what I can edit :)
