### ISSUE TITLE
Missing blacklisting handlers in DBManager

### ISSUE THREAD

**Issue by karelpak1** [kkrypt0nn/Python-Discord-Bot-Template#99]
**Describe the bug**
Missing handlers in DatabaseManager regarding blacklisting + schema? Which means, blacklisting is practically not functional. Also I read updates.md and this feature was removed (why?) in 6.0.0, sadly code is still present (in owner cog) and should be removed, if not planned for future use.

**To Reproduce**

1. /blacklist add {user}
2. /blacklist remove {user}
3. /blacklist show
4. See all errors

**Expected behavior**
Add/remove user to blacklist.
Show users in blacklist.

**Screenshots**
None

**Template Version**
[6.1.1 - 1bb7963](https://github.com/kkrypt0nn/Python-Discord-Bot-Template/tree/1bb796347bee9187a52faea27992a9ddcb73551f)

**Additional context**
None

**Comment by kkrypt0nn** [comment]
Planned to remove it, as it was my intention - there's no real reason to have blacklists especially storing them in a database like I previously did.

The problem is resource-wise it's not smart to make a database query every time a message is sent or slash command is executed. If someone wants to have one, would make sense to hard-code the IDs and check with those rather than making database queries.
